---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: goldpinger
  annotations:
    external-dns.alpha.kubernetes.io/target: internal.drmoo.io
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Node connectivity
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: mdi-connection
    gethomepage.dev/name: GoldPinger
    gethomepage.dev/app: goldpinger
spec:
  parentRefs:
    - name: envoy-internal
      namespace: networking
      sectionName: https
  hostnames:
    - goldpinger.drmoo.io
  rules:
    - backendRefs:
        - name: goldpinger
          port: 80
