---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres
spec:
  target:
    name: immich-postgres-secret
    template:
      engineVersion: v2
      data:
        s3.conf: |
          [global]
          repo2-s3-key=foo1
          repo2-s3-key-secret=foo2
        encryption.conf: |
          [global]
          repo2-cipher-pass=foo3
        init.sql: |
          \c immich
          BEGIN;
          ALTER DATABASE "immich" OWNER TO "immich";
          CREATE EXTENSION vector CASCADE;
          CREATE EXTENSION earthdistance CASCADE;
          COMMIT;
  data:
    - secretKey: foo
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: da91d5da-e654-4aa6-8e25-b3b80110830b
        property: username
