---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: bitwarden-apikey
  namespace: base
stringData:
  BW_CLIENTID: user.f357e616-47ee-4f36-97f7-acd500fc728f
  BW_CLIENTSECRET: 6jkfCgotvSdjvHZxaaGLN6dxzGxOLo
