kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: bitwarden-apikey
    namespace: base
stringData:
    BW_CLIENTID: ENC[AES256_GCM,data:Vf9mwv3qatyaCT0laQIjELIitS6AByKxpQ8dZLIHlpb6sK60hw/Vo/U=,iv:RQnUNKQnA0ShV80x1JEbEv+lQv9qyugV5lQBS9GxqkE=,tag:4NBQBrMHWsrws2tJsUc8YA==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:0SsTQ7mygBE982OYtlKVJnyrZeAfTBrzzTtJWvk6,iv:+QuiyySo0F+r1gjSTiOxgawZ1znewePPYD7jJ5C6YMY=,tag:Lmdi/SedodfgDLoGMwgD1Q==,type:str]
    BW_USER: ENC[AES256_GCM,data:z2ktyjWInHTAvBp5ajSEnWFJPA==,iv:QGizopmW7/FYILMxMDZlCen0/WmG7QEjRt5OTcU4P0k=,tag:Xkhx0qqE5gBvFPFPZJAoiQ==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:iWAR6MT9ivMBZlpG4Q==,iv:MjnS1YzhSvREigICuEdTwXWQwWVLXxEuvxfXJ4e8xfw=,tag:B0n4sm3lDjRSs69S4SwoyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jzax78wrm0emunjs6gev7ahxzlzuazd3j6fwql2q532ymnsm8qvqtps9te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKalMxV3czRlZ1RmFHT3ph
            RWhEeTFYRXBWeFE4Vk0xOTkvU2RXclE2eWdzCjV5d1daU3YzMHp6cDVtZXJaeHlN
            c1BMNTNUSFlLakRUbEgxQU1oUitBWmcKLS0tIFNzLzJTM0dHUEpldjYyc1pXbmdY
            VGpOTVpJWmh2UDAzZ05tZDJYRDFFNE0KjdCTZaCkuChaGjT2c6Dz+0ZYPXdWXFDI
            wP1ADiNxn6yq1YCB/3R5khfODs5npkkf2zp9U4h0u6QnszpaKMsatA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T04:30:57Z"
    mac: ENC[AES256_GCM,data:IXt4G0+F6Tcz85pnCd9fCcUTm4xszz2O9MYe/5hlRHvX3nuShlWzxcYDc5Sp6blMRr5Ph/T9O/boWRxaQ+/Xj8kNuqq6AgwzqSrRa5EJL7dkZvQXlF/Gq/zaj+VnIqAVUsSdlx3UHBwpw035hqtBcNPNmtotXEMA2fJIEOqvGTg=,iv:9kdPScGCRnqb0g/3uBxuDcYybvJGBCy/uJnoLflxyE0=,tag:DOiNnT4OvAmnc/A/OQxYsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
