kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: bitwarden-apikey
    namespace: base
stringData:
    BW_CLIENTID: ENC[AES256_GCM,data:Vf9mwv3qatyaCT0laQIjELIitS6AByKxpQ8dZLIHlpb6sK60hw/Vo/U=,iv:RQnUNKQnA0ShV80x1JEbEv+lQv9qyugV5lQBS9GxqkE=,tag:4NBQBrMHWsrws2tJsUc8YA==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:su01Nmh/C6ye7evFm3yUvSvGtNxrRjF4kmVqfrSv,iv:SQs7cAepq012VAqWhW0i9pqYfLJhsuRhi3RZsI3H420=,tag:9phzw70nIljfYVBTHl27gA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jzax78wrm0emunjs6gev7ahxzlzuazd3j6fwql2q532ymnsm8qvqtps9te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKalMxV3czRlZ1RmFHT3ph
            RWhEeTFYRXBWeFE4Vk0xOTkvU2RXclE2eWdzCjV5d1daU3YzMHp6cDVtZXJaeHlN
            c1BMNTNUSFlLakRUbEgxQU1oUitBWmcKLS0tIFNzLzJTM0dHUEpldjYyc1pXbmdY
            VGpOTVpJWmh2UDAzZ05tZDJYRDFFNE0KjdCTZaCkuChaGjT2c6Dz+0ZYPXdWXFDI
            wP1ADiNxn6yq1YCB/3R5khfODs5npkkf2zp9U4h0u6QnszpaKMsatA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T05:12:37Z"
    mac: ENC[AES256_GCM,data:c13bZoRr7dr280cyNyTBWkxbFkywgQkUeT+eG+WJEB5shuJe96Xo3gx6Pk0cdzB+pV1/Eu+rz/VsAK76MT4KUiM8WT9SRyklbbRH5UQex1kqAk0KpTCpoBm5+zBa9waFDZ/CBoroFJJSEg0F02wUUqcVC1X3nmcGsgrXQbPvNHg=,iv:yObxDLGtp+mzcpgzKs+2U0bW+SMFKMDdRnO5yAjKMbU=,tag:ywtRA3uObRWzNvtzRDDx5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
