kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: bitwarden-apikey
    namespace: base
stringData:
    BW_CLIENTID: ENC[AES256_GCM,data:Vf9mwv3qatyaCT0laQIjELIitS6AByKxpQ8dZLIHlpb6sK60hw/Vo/U=,iv:RQnUNKQnA0ShV80x1JEbEv+lQv9qyugV5lQBS9GxqkE=,tag:4NBQBrMHWsrws2tJsUc8YA==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:su01Nmh/C6ye7evFm3yUvSvGtNxrRjF4kmVqfrSv,iv:SQs7cAepq012VAqWhW0i9pqYfLJhsuRhi3RZsI3H420=,tag:9phzw70nIljfYVBTHl27gA==,type:str]
    #ENC[AES256_GCM,data:HecQTMhh/Nb0lOKD05liN3hxeaRn5DlhpuxFRScaZmjTdFrrR6B4Zr0=,iv:cCT/7UFmUZWVG4Zbt1i0IcGGPUEQBdqFyTLYWxgvoWU=,tag:NyzweRUxUNN1xJIxTVVFPg==,type:comment]
    BW_PASSWORD: ENC[AES256_GCM,data:aZwi6w49X1ap4x6VXw==,iv:hrPwzD9WRqA8ZpJxTMnnekfM77c2nEGYG4qbKTCRU/A=,tag:5h/BkCl6rGNcca606pFp7g==,type:str]
    #ENC[AES256_GCM,data:9vdLkO2EGih8HA0J3MF2VFiS040HFYpNh1dgJcWwMxdr2CIQL9l0SrMKulVvWbvd1kIlaM8RIiIQMdNWV8riNzvn7wuRkyvbzO4anZZSkBUN1Um8YHeDbkHRqS1Q2psa4tDjFkEOteGRGGiAga0fw//GS2hj4PSv9LmMRMNqk/guH8ABpg==,iv:Da2HUqXzSonaJunHSesArOZLiIwVX+gcEfrHWJha9sM=,tag:PdnkPlI8YWT8Sc587t33MA==,type:comment]
    BW_USERNAME: ENC[AES256_GCM,data:ayKfNSTZ2AVgWIMAOuit9KB6/Q==,iv:RnRPjvteJGhsSMB160K/ZUsiBbUC0iMGW2dGX99Hmeo=,tag:VwZ66lPCjf2hUVNMeoaklQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jzax78wrm0emunjs6gev7ahxzlzuazd3j6fwql2q532ymnsm8qvqtps9te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKalMxV3czRlZ1RmFHT3ph
            RWhEeTFYRXBWeFE4Vk0xOTkvU2RXclE2eWdzCjV5d1daU3YzMHp6cDVtZXJaeHlN
            c1BMNTNUSFlLakRUbEgxQU1oUitBWmcKLS0tIFNzLzJTM0dHUEpldjYyc1pXbmdY
            VGpOTVpJWmh2UDAzZ05tZDJYRDFFNE0KjdCTZaCkuChaGjT2c6Dz+0ZYPXdWXFDI
            wP1ADiNxn6yq1YCB/3R5khfODs5npkkf2zp9U4h0u6QnszpaKMsatA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T05:33:20Z"
    mac: ENC[AES256_GCM,data:YXBkQMIt4bOrvjKYZXpW+yolvlRiMzMg71WKKLOl9Ii/T2Jhy33KqYpDnbXDCjbhEIrzi/Q812swRjFpiqWdzRaYOfhbmtdIDh9VWJgivnJtf4DBGlGOzUs14EZhDrosBk2De0N6g6nv4MrBNnCZxE2xuEuZYzuH3FC5hxyIA6Q=,iv:Qxd8inijSqnn6j/rdlDeEHFoJNnbdld+27n2yjYFXbo=,tag:bp6V8EIFA3HMqd/3rwwF3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
