kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: bitwarden-apikey
    namespace: base
stringData:
    BW_CLIENTID: ENC[AES256_GCM,data:Vf9mwv3qatyaCT0laQIjELIitS6AByKxpQ8dZLIHlpb6sK60hw/Vo/U=,iv:RQnUNKQnA0ShV80x1JEbEv+lQv9qyugV5lQBS9GxqkE=,tag:4NBQBrMHWsrws2tJsUc8YA==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:0SsTQ7mygBE982OYtlKVJnyrZeAfTBrzzTtJWvk6,iv:+QuiyySo0F+r1gjSTiOxgawZ1znewePPYD7jJ5C6YMY=,tag:Lmdi/SedodfgDLoGMwgD1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jzax78wrm0emunjs6gev7ahxzlzuazd3j6fwql2q532ymnsm8qvqtps9te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKalMxV3czRlZ1RmFHT3ph
            RWhEeTFYRXBWeFE4Vk0xOTkvU2RXclE2eWdzCjV5d1daU3YzMHp6cDVtZXJaeHlN
            c1BMNTNUSFlLakRUbEgxQU1oUitBWmcKLS0tIFNzLzJTM0dHUEpldjYyc1pXbmdY
            VGpOTVpJWmh2UDAzZ05tZDJYRDFFNE0KjdCTZaCkuChaGjT2c6Dz+0ZYPXdWXFDI
            wP1ADiNxn6yq1YCB/3R5khfODs5npkkf2zp9U4h0u6QnszpaKMsatA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T04:33:29Z"
    mac: ENC[AES256_GCM,data:Idlw++5pMGqbuu07pQ/4M2mawavlF8goGo4UqaxgWhEihQVaie2DfDa/9IPZomlAMnvLo4zqvm2ss/SmII25+KFy9jGdWGcCvzoL/xpElXkl82v2PlbmssdZtPn8ETV94waSO3U91YsPsmlYby5zvAcVdgLHPwJmXWmPugXwmww=,iv:G+aVQ9TiZVhuLTv8v4O2NG5aUtAzb+Av4HYa2G4OzmI=,tag:4l5H7Dy3mG+IJKgvlDnMAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
