kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: bitwarden-apikey
    namespace: base
stringData:
    BW_CLIENTID: ENC[AES256_GCM,data:Vf9mwv3qatyaCT0laQIjELIitS6AByKxpQ8dZLIHlpb6sK60hw/Vo/U=,iv:RQnUNKQnA0ShV80x1JEbEv+lQv9qyugV5lQBS9GxqkE=,tag:4NBQBrMHWsrws2tJsUc8YA==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:0SsTQ7mygBE982OYtlKVJnyrZeAfTBrzzTtJWvk6,iv:+QuiyySo0F+r1gjSTiOxgawZ1znewePPYD7jJ5C6YMY=,tag:Lmdi/SedodfgDLoGMwgD1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jzax78wrm0emunjs6gev7ahxzlzuazd3j6fwql2q532ymnsm8qvqtps9te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKalMxV3czRlZ1RmFHT3ph
            RWhEeTFYRXBWeFE4Vk0xOTkvU2RXclE2eWdzCjV5d1daU3YzMHp6cDVtZXJaeHlN
            c1BMNTNUSFlLakRUbEgxQU1oUitBWmcKLS0tIFNzLzJTM0dHUEpldjYyc1pXbmdY
            VGpOTVpJWmh2UDAzZ05tZDJYRDFFNE0KjdCTZaCkuChaGjT2c6Dz+0ZYPXdWXFDI
            wP1ADiNxn6yq1YCB/3R5khfODs5npkkf2zp9U4h0u6QnszpaKMsatA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T04:38:34Z"
    mac: ENC[AES256_GCM,data:XKP1AlXsTQTRZbou1Dc0k5mXcJGJbOOeTPQ+qby396Uo1fKQ4qpfW61IW/FqlvT2xFNt9Wzo/pZinMoEWJ/yLfq3xngxcp7vNOVU1ZKByl+Y92srmdZqsK675HsgNn+r+sQhR+y+1s9m4lqYsASpTbe8vJABxikLkNAjSzgB9H0=,iv:gLoE9pDRdRSEdOoAiDa5YJuvCDIjpmd0cnIeAa83iRQ=,tag:+LCV6nqBG3RnTdIAjgaIOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
