kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: bitwarden-apikey
    namespace: base
stringData:
    BW_HOST: ENC[AES256_GCM,data:mD1b4GZ2eOT8jw6gOrVXEX9EkmkuVT4v2Cju,iv:gzV4ZAeULjQXhSbP1LjY7h5W7l0P9K28gs2wQwTOG/c=,tag:ahRgb7DU5L+ibg8qvWOEPg==,type:str]
    BW_CLIENTID: ENC[AES256_GCM,data:Vf9mwv3qatyaCT0laQIjELIitS6AByKxpQ8dZLIHlpb6sK60hw/Vo/U=,iv:RQnUNKQnA0ShV80x1JEbEv+lQv9qyugV5lQBS9GxqkE=,tag:4NBQBrMHWsrws2tJsUc8YA==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:su01Nmh/C6ye7evFm3yUvSvGtNxrRjF4kmVqfrSv,iv:SQs7cAepq012VAqWhW0i9pqYfLJhsuRhi3RZsI3H420=,tag:9phzw70nIljfYVBTHl27gA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jzax78wrm0emunjs6gev7ahxzlzuazd3j6fwql2q532ymnsm8qvqtps9te
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKalMxV3czRlZ1RmFHT3ph
            RWhEeTFYRXBWeFE4Vk0xOTkvU2RXclE2eWdzCjV5d1daU3YzMHp6cDVtZXJaeHlN
            c1BMNTNUSFlLakRUbEgxQU1oUitBWmcKLS0tIFNzLzJTM0dHUEpldjYyc1pXbmdY
            VGpOTVpJWmh2UDAzZ05tZDJYRDFFNE0KjdCTZaCkuChaGjT2c6Dz+0ZYPXdWXFDI
            wP1ADiNxn6yq1YCB/3R5khfODs5npkkf2zp9U4h0u6QnszpaKMsatA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T05:08:22Z"
    mac: ENC[AES256_GCM,data:Kw5a3h8Zeg+AzTiXaYH9zXaEizeq3qKSrhffOR6mil7SlfDIQR2Km9KIryFvgbSMBPT+xKYTATr6HsKzeCJE6KJGLZgeri3qBAxTtUfOtHJH312rr2Q4pHu+tQ7p1qeXWPlCDTNDBpl1YOfHtzioP5Tpp6fhs5BGQBO/QFpEMs4=,iv:xVf6oGmvKJms0qoPD1E8RG8AZVQUbuZlm8QDJrsYQi4=,tag:ikuCK+moyhK23qpwslAo3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
