---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app zwave
  namespace: &namespace home-automation
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
      namespace: base
    - name: rook-ceph-cluster
      namespace: storage
  components:
    - ../../../../common/volsync
  postBuild:
    substitute:
      APP: *app
      PVC_NAME: zwave-blockstorage
      VOLSYNC_CAPACITY: 10Gi
      VOLSYNC_SCHEDULE: "51 * * * *"
  path: ./kubernetes/homelab/apps/home-automation/zwave/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: profmoo-home
    namespace: flux-system
  timeout: 5m
  interval: 30m
  retryInterval: 2m
  wait: false
