---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  annotations:
    external-dns.alpha.kubernetes.io/target: internal.drmoo.io
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Grafana"
    gethomepage.dev/description: "Observability (username:password)"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "grafana"
    gethomepage.dev/app: "grafana"
    gethomepage.dev/instance: "homepage-internal"
    gethomepage.dev/widget.type: "grafana"
    gethomepage.dev/widget.url: "http://grafana-service.observability.svc.cluster.local:3000"
    gethomepage.dev/widget.username: "username"
    gethomepage.dev/widget.password: "password"
spec:
  parentRefs:
    - name: envoy-internal
      namespace: networking
      sectionName: https
  hostnames:
    - grafana.drmoo.io
  rules:
    - backendRefs:
        - name: grafana-service
          port: 3000
