---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app qbittorrent
  namespace: &namespace media
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
      namespace: base
    - name: rook-ceph-cluster
      namespace: storage
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: qbittorrent
      namespace: media
  components:
    - ../../../../common/volsync
  postBuild:
    substitute:
      APP: *app
      PVC_NAME: qbittorrent
      VOLSYNC_CAPACITY: 5Gi
      VOLSYNC_SCHEDULE: "15 * * * *"
  path: ./kubernetes/homelab/apps/media/qbittorrent/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: profmoo-home
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tqm
  namespace: &namespace media
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/homelab/apps/media/qbittorrent/tqm
  prune: true
  sourceRef:
    kind: GitRepository
    name: profmoo-home
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app qbittorrent-exporter
  namespace: &namespace media
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: qbittorrent
  path: ./kubernetes/homelab/apps/media/qbittorrent/exporter
  prune: true
  sourceRef:
    kind: GitRepository
    name: profmoo-home
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app qui
  namespace: &namespace media
spec:
  targetNamespace: *namespace
  components:
    - ../../../../common/volsync
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
      namespace: base
    - name: rook-ceph-cluster
      namespace: storage
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: qui
      namespace: media
  interval: 1h
  path: ./kubernetes/homelab/apps/media/qbittorrent/qui
  postBuild:
    substitute:
      APP: qui
      PVC_NAME: qui
      VOLSYNC_CAPACITY: 2Gi
      VOLSYNC_SCHEDULE: "18 * * * *"
  prune: true
  sourceRef:
    kind: GitRepository
    name: profmoo-home
    namespace: flux-system
  wait: false
