---
apiVersion: v1
kind: Service
metadata:
  name: ssh-bastion
spec:
  # NOTE: We use a LoadBalancer service here because the envoy listener is only configured for http/https right now
  # This is easier than adding a new listener on the gateway for 2222, which feels risky.
  type: LoadBalancer
  loadBalancerIP: 192.168.8.140
  selector:
    app: ssh-bastion
  ports:
    - port: 2222
      targetPort: 2222
      name: ssh
