---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helm-release.yaml
  - ./oci-repository.yaml
configMapGenerator:
  - name: tqm-configmap
    files:
      - ./resources/config.yaml
generatorOptions:
  disableNameSuffixHash: true
