---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json                                                                                                                                            !10083
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: obkiddos-1
  annotations:
    external-dns.alpha.kubernetes.io/target: obkiddos-1.drmoo.io
spec:
  hostnames:
    - obkiddos-1.drmoo.io
  parentRefs:
    - name: envoy-external
      namespace: networking
      sectionName: https
  rules:
    - backendRefs:
        - name: mc-router
          port: 25565
      matches:
        - path:
            type: PathPrefix
            value: /
