---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minecraft-3
  annotations:
    external-dns.alpha.kubernetes.io/target: external.drmoo.io
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Minecraft 3
    gethomepage.dev/group: Games
    gethomepage.dev/icon: minecraft
    gethomepage.dev/name: "OBKiddos 3 Dynamp"
    gethomepage.dev/app: minecraft-3
    gethomepage.dev/instance: homepage-external
spec:
  parentRefs:
    - name: envoy-external
      namespace: networking
      sectionName: https
  hostnames:
    - obkiddos-3.drmoo.io
  rules:
    - backendRefs:
        - name: minecraft-3
          port: 8123
