---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage-internal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage-internal
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      serviceAccount: homepage-internal
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v1.10.1
          ports:
            - containerPort: 3000
              name: homepage
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "home.drmoo.io,localhost"
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
          volumeMounts:
            - name: homepage-config-volume
              # NOTE: Homepage expects this at a specific location, which we've matched here.
              mountPath: /app/config
            - name: logs
              mountPath: /app/config/logs
      volumes:
        - name: homepage-config-volume
          configMap:
            name: homepage-internal-config
        - name: logs
          emptyDir: {}
