---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./service-account.yaml
  - ./cluster-role.yaml
  - ./cluster-role-binding.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./http-route.yaml
configMapGenerator:
  - name: homepage-external-config
    files:
      - bookmarks.yaml=./config/bookmarks.yaml
      - custom.css=./config/custom.css
      - custom.js=./config/custom.js
      - docker.yaml=./config/docker.yaml
      - kubernetes.yaml=./config/kubernetes.yaml
      - proxmox.yaml=./config/proxmox.yaml
      - services.yaml=./config/services.yaml
      - settings.yaml=./config/settings.yaml
      - widgets.yaml=./config/widgets.yaml
generatorOptions:
  disableNameSuffixHash: true
