---
apiVersion: v1
kind: Service
metadata:
  name: homepage-external
spec:
  selector:
    app.kubernetes.io/name: homepage-external
  ports:
    - protocol: TCP
      name: homepage
      port: 3000
      targetPort: 3000
  type: ClusterIP
