---
# Docs for this file can be found here:
# https://gethomepage.dev/widgets/
- Home:
    - Jellyfin:
        href: https://jellyfin.drmoo.io
        icon: jellyfin
        description: Media server (admin:)
        widget:
          type: jellyfin
          url: https://jellyfin.drmoo.io
          key: f58cd19c3e6749f585f580fb11d7d180
    - Jellyseerr:
        href: https://request.drmoo.io
        icon: jellyseerr
        description: Request system
        widget:
          type: jellyseerr
          url: http://jellyseerr.media.svc.cluster.local:80
          key: MTc1ODQyMzQ3MTg3NDUyZTg0NWM4LTJhYjYtNDJkZC1hNDI4LWE1OTQ3ODZmMGRmYQ==
    - Gatus:
        href: https://status.drmoo.io
        icon: gatus
        description: Status page
        widget:
          type: gatus
          url: https://status.drmoo.io
    - Home Assistant:
        href: https://hass.drmoo.io
        icon: homeassistant
        description: Home assistant
        widget:
          type: homeassistant
          url: http://home-assistant.home-automation.svc.cluster.local:8123
          key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjNDE5MWY1ODY0ZjA0NTRmYjgxYzNiMTM3NjU4NjI1OCIsImlhdCI6MTc1NzE5MTA4NSwiZXhwIjoyMDcyNTUxMDg1fQ.PAFiFMVzkBy1oZiIqRsgr5dCG4a_TelEo2z5U8BpeIQ
    - Zigbee2MQTT:
        href: https://zigbee.drmoo.io
        description: Zigbee coordinator
    - Zigbee Radio:
        href: http://192.168.1.148
        description: Zigbee radio webpage
    - Mosquitto:
        href: https://mosquitto.drmoo.io
        description: MQTT Broker
- Infrastructure:
    - Rook:
        href: https://rook.drmoo.io
        icon: mdi-database
        description: Rook storage cluster
    - Cilium:
        href: https://hubble.drmoo.io
        icon: mdi-lan
        description: Network packet visualization
    - Grafana:
        href: https://grafana.drmoo.io
        icon: grafana
        description: Observability (username:password)
        widget:
          type: grafana
          url: http://grafana-service.observability.svc.cluster.local:3000
          username: username
          password: password
    - Prometheus:
        href: https://prometheus.drmoo.io
        icon: prometheus
        description: Metrics
        widget:
          type: prometheus
          url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
          fields: ["targets_up", "targets_down", "targets_total"]
    - AlertManager:
        href: https://alertmanager.drmoo.io
        icon: alertmanager
        description: Alerts
    - GoldPinger:
        href: https://goldpinger.drmoo.io
        icon: mdi-connection
        description: Node connectivity
- Torrents:
    - Prowlarr:
        href: https://prowlarr.drmoo.io
        icon: prowlarr.png
        description: Tracker indexer wrapper (admin:admin)
        widget:
          type: prowlarr
          url: http://prowlarr.media.svc.cluster.local:80
          key: foobarbazfoobarbazfoobarbazfooba
    - Radarr:
        href: https://radarr.drmoo.io
        icon: radarr.png
        description: Movie torrent manager (admin:admin)
        widget:
          type: radarr
          url: http://radarr.media.svc.cluster.local:80
          key: foobarbazfoobarbazfoobarbazfooba
    - Sonarr:
        href: https://sonarr.drmoo.io
        icon: sonarr.png
        description: TV series torrent manager (admin:admin)
        widget:
          type: sonarr
          url: http://sonarr.media.svc.cluster.local:80
          key: foobarbazfoobarbazfoobarbazfooba
    - Lidarr:
        href: https://lidarr.drmoo.io
        icon: lidarr.png
        description: TV series torrent manager (admin:admin)
        widget:
          type: lidarr
          url: http://lidarr.media.svc.cluster.local:80
          key: foobarbazfoobarbazfoobarbazfooba
    - qBittorrent:
        href: https://qb.drmoo.io
        icon: qbittorrent
        description: Torrent downloader (admin:adminadmin)
        widget:
          type: qbittorrent
          url: http://qbittorrent.media.svc.cluster.local:8080
          username: admin
          password: adminadmin
    - Betanin:
        href: http://betanin.drmoo.io
        icon: betanin
        description: Music tagging (user:pass)
- Other:
    - Unifi:
        href: http://192.168.1.1
        icon: unifi
    - TrueNAS:
        href: http://truenas.local
        icon: truenas
        description: TrueNas server
        widget:
          type: truenas
          url: http://192.168.1.26
          key: 1-WYckrNh6X7L1w3Bhwm8PUGn6N3n1JCjXsEUWnD870nhloTnqeVuiFbTHs6CQfAyF
    - TrueNAS OOBM:
        href: http://192.168.1.54
        icon: truenas
    - Compute-1:
        href: http://pve.0.internal.drmoo.io:8006
        icon: proxmox
        description: (root:admin)
    - Compute-2:
        href: http://pve.1.internal.drmoo.io:8006
        icon: proxmox
        description: (root:admin)
    - Compute-1 iDRAC:
        href: http://192.168.1.120
        icon: dell
        description: (root:calvin)
    - Compute-2 iDRAC:
        href: http://192.168.1.102
        icon: dell
        description: (root:MA33M93PFYX3)
    - Compute-3:
        href: http://192.168.1.187
        icon: supermicro
        description: (ADMIN:ADMIN)
    - Minecraft:
        href: udp://minecraft-3.games.svc.cluster.local:25565
        icon: minecraft
        description: OBKiddos 3
        widget:
          type: minecraft
          url: udp://minecraft-3.games.svc.cluster.local:25565
    - Minecraft:
        href: udp://minecraft-2.games.svc.cluster.local:25565
        icon: minecraft
        description: OBKiddos 2
        widget:
          type: minecraft
          url: udp://minecraft-2.games.svc.cluster.local:25565
    - Minecraft:
        href: udp://minecraft-1.games.svc.cluster.local:25565
        icon: minecraft
        description: OBKiddos 1
        widget:
          type: minecraft
          url: udp://minecraft-1.games.svc.cluster.local:25565
