---
address: 0.0.0.0
port: 9348
timeout: 30
hosts:
  192.168.1.187:
    username: ADMIN
    password: ADMIN
  192.168.1.120:
    username: root
    password: calvin
    use_basic_auth: true
metrics:
  all: true
