---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flux-operator
  annotations:
    external-dns.alpha.kubernetes.io/target: internal.drmoo.io
spec:
  parentRefs:
    - name: envoy-internal
      namespace: networking
      sectionName: https
  hostnames:
    - flux.drmoo.io
  rules:
    - backendRefs:
        - name: flux-operator
          namespace: flux-system
          port: 9080
      matches:
        - path:
            type: PathPrefix
            value: /
