---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui
spec:
  target:
    name: qui-secret
    template:
      engineVersion: v2
      data:
        QUI__SESSION_SECRET: "{{ .QUI_SESSION_SECRET }}"
  data:
    - secretKey: QUI__SESSION_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 9a07d31f-7f3a-48e9-b977-b3ac00adf735
        property: SESSION_SECRET_KEY
