---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble-ui
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Hubble"
    gethomepage.dev/description: "Network packet visualization"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "mdi-lan"
    gethomepage.dev/instance: "homepage-internal"
spec:
  hostnames:
    - hubble.drmoo.io
  parentRefs:
    - name: envoy-internal
      namespace: networking
      sectionName: https
  rules:
    - backendRefs:
        - name: hubble-ui
          namespace: cilium
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
