---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: movary
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      movary:
        containers:
          app:
            image:
              repository: leepeuker/movary
              tag: 0.69.0
            envFrom:
              - secretRef:
                  name: movary
            env:
              TIMEZONE: America/New_York
              DATABASE_MODE: sqlite
              TMDB_ENABLE_IMAGE_CACHING: '1' # Enable to prevent rate limit issues
              ENV: 'production'
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        # Needed to set to 3000, per the creator's recommendation:
        # https://github.com/leepeuker/movary/issues/632#issuecomment-2657274607
        runAsNonRoot: true
        runAsUser: 3000
        runAsGroup: 3000
        fsGroup: 3000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: movary
        ports:
          http:
            port: 8080
    route:
      app:
        hostnames:
          - "movary.drmoo.io"
        parentRefs:
          - name: envoy-external
            namespace: networking
            sectionName: https
    persistence:
      config:
        existingClaim: movary
        advancedMounts:
          movary:
            app:
              - path: /app/storage
