---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafana-dashboard.yaml
  - ./oci-repository.yaml
  - ./helm-release.yaml
  - ./prometheus-rule.yaml
  - ./pod-monitor.yaml
  - ./webhook
