---
# Docs for this file can be found here:
# https://gethomepage.dev/widgets/
- Home:
    - Zigbee Radio:
        href: http://192.168.1.148
        description: Zigbee radio webpage
- Other:
    - Unifi:
        href: http://192.168.1.1
        icon: unifi
    - TrueNAS:
        href: http://truenas.local
        icon: truenas
        description: TrueNas server
        widget:
          type: truenas
          url: http://192.168.1.26
          key: 1-WYckrNh6X7L1w3Bhwm8PUGn6N3n1JCjXsEUWnD870nhloTnqeVuiFbTHs6CQfAyF
    - TrueNAS OOBM:
        href: http://192.168.1.54
        icon: truenas
    - Compute-1:
        href: http://pve.0.internal.drmoo.io:8006
        icon: proxmox
        description: (root:admin)
    - Compute-2:
        href: http://pve.1.internal.drmoo.io:8006
        icon: proxmox
        description: (root:admin)
    - Compute-1 iDRAC:
        href: http://192.168.1.120
        icon: dell
        description: (root:calvin)
    - Compute-2 iDRAC:
        href: http://192.168.1.102
        icon: dell
        description: (root:MA33M93PFYX3)
    - Compute-3 iDRAC:
        href: http://192.168.1.187
        icon: supermicro
        description: (ADMIN:ADMIN)
