---
title: Moo's Pasture
instanceName: homepage-internal
logpath: /tmp
target: _self
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
headerStyle: clean
