---
- datetime:
    text_size: xl
    format:
      hour12: true
      timeStyle: short
- openmeteo:
    label: Hoboken
    latitude: 40.7440
    longitude: -74.0324
    units: imperial
    cache: 5
    # NOTE: Docs here: https://gethomepage.dev/latest/widgets/info/kubernetes/
- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "cluster"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
