---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: neko-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: |-
          {{ .root_username }}
        NEKO_MEMBER_MULTIUSER_USER_PASSWORD: |-
          {{ .root_password }}
  refreshInterval: 15m
  data:
    - secretKey: root_username
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: da91d5da-e654-4aa6-8e25-b3b80110830b
        property: username
    - secretKey: root_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: da91d5da-e654-4aa6-8e25-b3b80110830b
        property: password
