---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: neko
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: neko
  values:
    controllers:
      neko:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/m1k1o/neko/firefox
              tag: "3.0.10"
            env:
              NEKO_SCREEN: 1920x1080@30
              NEKO_PROXY: "true"
              NEKO_TCPMUX: &mux "5101"
              NEKO_UDPMUX: *mux
              NEKO_ICELITE: "true"
              NEKO_NAT1TO1: 192.168.8.133
              NEKO_SESSION_HEARTBEAT_INTERVAL: 30
            envFrom:
              - secretRef:
                  name: neko-secret
            resources:
              requests:
                cpu: 10m
    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 192.168.8.133
        ports:
          http:
            port: 80
            targetPort: 8080
          mux:
            port: &port 5101
          muxudp:
            port: *port
            protocol: UDP
    route:
      app:
        hostnames:
          - neko.drmoo.io
        parentRefs:
          - name: envoy-external
            namespace: networking
            sectionName: https
    persistence:
      config:
        name: neko-firefox-config
        type: configMap
        advancedMounts:
          neko:
            neko:
              - path: /usr/lib/firefox/distribution/policies.json
                readOnly: true
                subPath: policies.json
