---
# Docs for this file can be found here:
# https://gethomepage.dev/widgets/
- Home:
    - Gatus:
        href: https://status.drmoo.io
        icon: gatus
        description: Status page
        widget:
          type: gatus
          url: https://status.drmoo.io
    - Zigbee Radio:
        href: http://192.168.1.148
        description: Zigbee radio webpage
    - Mosquitto:
        href: https://mosquitto.drmoo.io
        description: MQTT Broker
- Infrastructure:
    - Rook:
        href: https://rook.drmoo.io
        icon: mdi-database
        description: Rook storage cluster
    - Cilium:
        href: https://hubble.drmoo.io
        icon: mdi-lan
        description: Network packet visualization
    - Grafana:
        href: https://grafana.drmoo.io
        icon: grafana
        description: Observability (username:password)
        widget:
          type: grafana
          url: http://grafana-service.observability.svc.cluster.local:3000
          username: username
          password: password
    - Prometheus:
        href: https://prometheus.drmoo.io
        icon: prometheus
        description: Metrics
        widget:
          type: prometheus
          url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
          fields: ["targets_up", "targets_down", "targets_total"]
    - AlertManager:
        href: https://alertmanager.drmoo.io
        icon: alertmanager
        description: Alerts
    - GoldPinger:
        href: https://goldpinger.drmoo.io
        icon: mdi-connection
        description: Node connectivity
- Other:
    - Unifi:
        href: http://192.168.1.1
        icon: unifi
    - TrueNAS:
        href: http://truenas.local
        icon: truenas
        description: TrueNas server
        widget:
          type: truenas
          url: http://192.168.1.26
          key: 1-WYckrNh6X7L1w3Bhwm8PUGn6N3n1JCjXsEUWnD870nhloTnqeVuiFbTHs6CQfAyF
    - TrueNAS OOBM:
        href: http://192.168.1.54
        icon: truenas
    - Compute-1:
        href: http://pve.0.internal.drmoo.io:8006
        icon: proxmox
        description: (root:admin)
    - Compute-2:
        href: http://pve.1.internal.drmoo.io:8006
        icon: proxmox
        description: (root:admin)
    - Compute-1 iDRAC:
        href: http://192.168.1.120
        icon: dell
        description: (root:calvin)
    - Compute-2 iDRAC:
        href: http://192.168.1.102
        icon: dell
        description: (root:MA33M93PFYX3)
    - Compute-3 iDRAC:
        href: http://192.168.1.187
        icon: supermicro
        description: (ADMIN:ADMIN)
    - Minecraft:
        href: udp://minecraft-3.games.svc.cluster.local:25565
        icon: minecraft
        description: OBKiddos 3
        widget:
          type: minecraft
          url: udp://minecraft-3.games.svc.cluster.local:25565
    - Minecraft:
        href: udp://minecraft-2.games.svc.cluster.local:25565
        icon: minecraft
        description: OBKiddos 2
        widget:
          type: minecraft
          url: udp://minecraft-2.games.svc.cluster.local:25565
    - Minecraft:
        href: udp://minecraft-1.games.svc.cluster.local:25565
        icon: minecraft
        description: OBKiddos 1
        widget:
          type: minecraft
          url: udp://minecraft-1.games.svc.cluster.local:25565
