---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-1
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: minecraft-1
  # NOTE: Values here: https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml
  values:
    resources:
      requests:
        memory: 4Gi
        cpu: 1000m
      limits:
        memory: 8Gi
        cpu: 4000m
    workloadAsStatefulSet: true
    strategyType: RollingUpdate
    minecraftServer:
      # NOTE: This tells the container to override the server.properties file on disk. Be careful with this.
      overrideServerProperties: true
      # This must be overridden, since we can't accept this for the user.
      eula: "TRUE"
      # One of: LATEST, SNAPSHOT, or a specific version (ie: "1.7.9").
      # renovate: datasource=custom.minecraft-release
      version: 1.21.11
      # This can be one of "VANILLA", "FORGE", "SPIGOT", "BUKKIT", "PAPER", "FTBA", "SPONGEVANILLA", "CURSEFORGE", etc.
      type: "FABRIC"
      # One of: peaceful, easy, normal, and hard
      difficulty: normal
      # This sets the maximum possible size in blocks, expressed as a radius, that the world border can obtain.
      maxWorldSize: 20000
      # If you adjust this, you may need to adjust resources.requests above to match.
      memory: 6000M
      # One of: creative, survival, adventure, spectator
      gameMode: survival
      # Message of the Day
      motd: "Moo's Pasture 1 - Moo, Moo, Bitch"
      # A comma-separated list of player names to whitelist.
      whitelist: ProfMoo,bamxmejia,KittyDonut1009,00Rem00,Seanzz,The9thCobra,linderson9
      # A comma-separated list of player names who should be admins.
      ops: ProfMoo
      modrinth:
        projects:
          # Lithium - this is the server-side mod which increases performance (but tries to keep vanilla behavior)
          - 'fabric:lithium'
          - 'fabric:fabricexporter'
          - 'fabric:spark'
        # Specifies whether to download Modrinth dependencies. The allowed values are: none, required, optional
        downloadDependencies: required
        # The version type is used to determine the newest version to use from each project. The allowed values are: release, beta, alpha
        allowedVersionType: release
      rcon:
        enabled: true
        withGeneratedPassword: false
        port: 25575
        existingSecret: rcon-secret-1
        secretKey: rcon-password
      # These options allow you to expose another port from the Minecraft server, plugins such
      # as dynmap (8123) and bluemap (8100) will require this for access to their web interfaces
      extraPorts:
        - name: metrics
          containerPort: 25585
          protocol: TCP
          # For some reason, the service needs to be enabled for the chart to add the port to the pod.
          # So we use a pod monitor, but need this useless service. *shrugs*.
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 25585
    serviceAnnotations:
      mc-router.itzg.me/externalServerName: obkiddos-1.drmoo.io
      gatus.home-operations.com/endpoint: |-
        url: tcp://obkiddos-1.drmoo.io:25565
        group: minecraft
        conditions:
          - "[CONNECTED] == true"
      gethomepage.dev/enabled: "true"
      gethomepage.dev/name: "OBKiddos 1"
      gethomepage.dev/description: "Minecraft server"
      gethomepage.dev/group: "Games"
      gethomepage.dev/icon: "minecraft"
      gethomepage.dev/instance: "homepage-internal"
      gethomepage.dev/widget.type: "minecraft"
      gethomepage.dev/widget.url: "udp://minecraft-1.games.svc.cluster.local:25565"
    persistence:
      dataDir:
        enabled: true
        Size: 50Gi
        accessModes:
          - ReadWriteOnce
        existingClaim: minecraft-1
