---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./service-account.yaml
  - ./cluster-role-binding.yaml
  - ./daemon-set.yaml
  - ./service.yaml
  - ./http-route.yaml
